# Generated by Django 4.2.2 on 2023-07-07 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ariza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('talaba_id', models.CharField(max_length=10)),
                ('viloyat', models.CharField(max_length=100)),
                ('tuman', models.CharField(max_length=100)),
                ('fakultet', models.CharField(max_length=100)),
                ('yonalish', models.CharField(max_length=100)),
                ('kurs', models.CharField(max_length=100)),
                ('pasport_rasm', models.FileField(upload_to='rasmlar/')),
                ('nogironlig', models.CharField(blank=True, max_length=100)),
                ('nogironlig_fayl', models.FileField(blank=True, upload_to='nogironlig/')),
                ('chin_yetim', models.CharField(blank=True, max_length=100)),
                ('chin_yetim_fayl', models.FileField(blank=True, upload_to='chin_yetim/')),
                ('daftar_turishi', models.CharField(blank=True, max_length=100)),
                ('daftar_turishi_fayl', models.FileField(blank=True, upload_to='daftar_turishi/')),
                ('boquvchisini_yoqotgan', models.CharField(blank=True, max_length=100)),
                ('boquvchisini_yoqotgan_fayl', models.FileField(blank=True, upload_to='boquvchisini_yoqotgan/')),
                ('tasdiqlash', models.CharField(blank=True, max_length=100)),
                ('radetish', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Imtiyoz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('talaba_id', models.CharField(max_length=10)),
                ('nomi', models.CharField(max_length=100)),
                ('file', models.FileField(upload_to='imtiyoz/')),
            ],
        ),
    ]
