# Generated by Django 4.2.2 on 2023-06-21 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ariza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viloyat', models.CharField(max_length=100)),
                ('tuman', models.CharField(max_length=100)),
                ('fakultet', models.CharField(max_length=100)),
                ('yonalish', models.CharField(max_length=100)),
                ('kurs', models.CharField(max_length=100)),
                ('pasport_rasm', models.FileField(upload_to='pasport_rasm')),
                ('nogironlig', models.CharField(max_length=100)),
                ('chin_yetim', models.CharField(max_length=100)),
                ('daftar_turishi', models.CharField(max_length=100)),
                ('boquvchisini_yoqotgan', models.CharField(max_length=100)),
            ],
        ),
    ]
