# Generated by Django 4.2.2 on 2023-07-07 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ariza', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ariza',
            name='boquvchisini_yoqotgan',
        ),
        migrations.RemoveField(
            model_name='ariza',
            name='boquvchisini_yoqotgan_fayl',
        ),
        migrations.RemoveField(
            model_name='ariza',
            name='chin_yetim',
        ),
        migrations.RemoveField(
            model_name='ariza',
            name='chin_yetim_fayl',
        ),
        migrations.RemoveField(
            model_name='ariza',
            name='daftar_turishi',
        ),
        migrations.RemoveField(
            model_name='ariza',
            name='daftar_turishi_fayl',
        ),
        migrations.RemoveField(
            model_name='ariza',
            name='nogironlig',
        ),
        migrations.RemoveField(
            model_name='ariza',
            name='nogironlig_fayl',
        ),
        migrations.AddField(
            model_name='ariza',
            name='xulosa',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
