# Generated by Django 4.2.2 on 2023-07-18 17:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ariza', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ariza',
            old_name='file',
            new_name='imtiyoz_file',
        ),
        migrations.RenameField(
            model_name='ariza',
            old_name='nomi',
            new_name='imtiyoz_nomi',
        ),
        migrations.AddField(
            model_name='barcha_tolov',
            name='sana',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tark_etgan',
            name='sana',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
