# Generated by Django 4.2.2 on 2023-07-15 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ariza', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tolov',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('talaba_id', models.CharField(max_length=100)),
                ('narhi', models.CharField(max_length=100)),
                ('kivtansiya', models.FileField(upload_to='kivtansiya/')),
            ],
        ),
    ]
