# Generated by Django 4.2.2 on 2023-07-04 10:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ariza', '0002_alter_ariza_boquvchisini_yoqotgan_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ariza',
            name='radetish',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='ariza',
            name='talaba_id',
            field=models.CharField(default=django.utils.timezone.now, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ariza',
            name='tasdiqlash',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
