# Generated by Django 4.2.2 on 2023-07-15 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ariza', '0002_tolov'),
    ]

    operations = [
        migrations.CreateModel(
            name='Barcha_tolov',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barcha', models.CharField(max_length=100)),
                ('oylik', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='tolov',
            name='tasqiqlash',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
