# Generated by Django 4.2.2 on 2023-07-18 17:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ariza', '0002_rename_file_ariza_imtiyoz_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ariza',
            name='kocha',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
