# Generated by Django 4.2.2 on 2023-07-18 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ariza', '0003_ariza_kocha'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ariza',
            name='radetish',
        ),
    ]
