# Generated by Django 4.2.2 on 2023-07-15 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ariza', '0003_barcha_tolov_tolov_tasqiqlash'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tark_etgan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('talaba_id', models.CharField(max_length=100)),
                ('tark_etish', models.CharField(max_length=100)),
            ],
        ),
    ]
