# Generated by Django 4.2.2 on 2023-07-18 19:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ariza', '0004_remove_ariza_radetish'),
    ]

    operations = [
        migrations.AddField(
            model_name='tark_etgan',
            name='sabab',
            field=models.CharField(default=django.utils.timezone.now, max_length=300),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ariza',
            name='talaba_id',
            field=models.CharField(max_length=100),
        ),
    ]
