# Generated by Django 4.2.2 on 2023-07-19 15:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ariza', '0005_tark_etgan_sabab_alter_ariza_talaba_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='ariza',
            name='pasport_raqam',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ariza',
            name='pasport_serya',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='barcha_tolov',
            name='hisob_raqam',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='barcha_tolov',
            name='barcha',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='barcha_tolov',
            name='oylik',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
