# Generated by Django 4.2.2 on 2023-07-19 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ariza', '0006_ariza_pasport_raqam_ariza_pasport_serya_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ariza',
            old_name='pasport_raqam',
            new_name='pasport_serya_raqam',
        ),
        migrations.RemoveField(
            model_name='ariza',
            name='pasport_serya',
        ),
    ]
