# Generated by Django 4.2.2 on 2023-07-19 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ariza', '0007_rename_pasport_raqam_ariza_pasport_serya_raqam_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='barcha_tolov',
            name='boshlanginch_tolov',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
