# Generated by Django 4.2.2 on 2023-07-21 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ariza', '0008_barcha_tolov_boshlanginch_tolov'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barcha_tolov',
            name='barcha',
            field=models.CharField(max_length=100),
        ),
    ]
