# Generated by Django 4.2.2 on 2023-07-22 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ariza', '0009_alter_barcha_tolov_barcha'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('talaba_id', models.CharField(blank=True, max_length=10)),
                ('familiya', models.CharField(blank=True, max_length=100)),
                ('ism', models.CharField(blank=True, max_length=100)),
                ('sharif', models.CharField(blank=True, max_length=200)),
                ('manzil', models.CharField(blank=True, max_length=100)),
                ('fakultet', models.CharField(blank=True, max_length=100)),
                ('yonalish', models.CharField(blank=True, max_length=10)),
                ('kurs', models.CharField(blank=True, max_length=100)),
                ('guruh', models.CharField(blank=True, max_length=100)),
                ('ttj_nomer', models.CharField(blank=True, max_length=100)),
                ('qavat', models.CharField(blank=True, max_length=10)),
                ('xona', models.CharField(blank=True, max_length=100)),
                ('sana', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Rasm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('talaba_id', models.CharField(blank=True, max_length=10)),
                ('link', models.CharField(blank=True, max_length=100)),
                ('rasm', models.FileField(upload_to='qrcode/')),
            ],
        ),
        migrations.CreateModel(
            name='Shartnoma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('talaba_id', models.CharField(blank=True, max_length=10)),
                ('talaba_f_i_sh', models.CharField(blank=True, max_length=100)),
                ('manzil', models.CharField(blank=True, max_length=100)),
                ('iib_manzil', models.CharField(blank=True, max_length=200)),
                ('pasport', models.CharField(blank=True, max_length=100)),
                ('ttj_nomer', models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
