# Generated by Django 4.2.2 on 2023-07-22 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ariza', '0010_order_rasm_shartnoma'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tolov',
            name='kivtansiya',
            field=models.FileField(blank=True, upload_to='kivtansiya/'),
        ),
    ]
