# Generated by Django 4.2.2 on 2023-07-22 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ariza', '0011_alter_tolov_kivtansiya'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tolov',
            name='kivtansiya',
            field=models.FileField(upload_to='kivtansiya/'),
        ),
    ]
