# Generated by Django 4.2.2 on 2023-07-23 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ariza', '0012_alter_tolov_kivtansiya'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ariza',
            name='imtiyoz_file',
            field=models.FileField(blank=True, upload_to='imtiyoz/'),
        ),
        migrations.AlterField(
            model_name='ariza',
            name='imtiyoz_nomi',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
