# Generated by Django 4.2.2 on 2023-07-24 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ariza', '0013_alter_ariza_imtiyoz_file_alter_ariza_imtiyoz_nomi'),
    ]

    operations = [
        migrations.CreateModel(
            name='Imtiyoz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imtiyoz_nomi', models.CharField(max_length=100)),
                ('imtiyoz_file', models.FileField(upload_to='imtiyoz/')),
                ('tasdiqlash', models.CharField(blank=True, max_length=100)),
                ('xulosa', models.CharField(blank=True, max_length=1000)),
                ('sana', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='ariza',
            name='imtiyoz_file',
        ),
        migrations.RemoveField(
            model_name='ariza',
            name='imtiyoz_nomi',
        ),
    ]
