# Generated by Django 4.2.2 on 2023-07-24 09:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ariza', '0014_imtiyoz_remove_ariza_imtiyoz_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='imtiyoz',
            name='talaba_id',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
