# Generated by Django 4.2.2 on 2023-07-25 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ariza', '0017_tark_etgan_first_name_tark_etgan_last_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='talaba_id',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='rasm',
            name='talaba_id',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='shartnoma',
            name='talaba_id',
            field=models.CharField(max_length=100),
        ),
    ]
