# Generated by Django 4.2.2 on 2023-07-26 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ariza', '0019_order_link'),
    ]

    operations = [
        migrations.RenameField(
            model_name='barcha_tolov',
            old_name='hisob_raqam',
            new_name='ttj_soni',
        ),
        migrations.RenameField(
            model_name='barcha_tolov',
            old_name='barcha',
            new_name='yillik_tolv',
        ),
        migrations.AddField(
            model_name='barcha_tolov',
            name='xonalar_soni',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='barcha_tolov',
            name='yigilgan_summa',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
