# Generated by Django 4.2.2 on 2023-07-31 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ariza', '0022_imtiyoz_first_name_imtiyoz_last_name_imtiyoz_sharif'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='tasdiqlash',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
