# Generated by Django 4.2.2 on 2023-08-03 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ariza', '0024_alter_order_manzil_alter_order_qavat_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='ttj_manzil',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
