# Generated by Django 4.2.2 on 2023-08-03 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ariza', '0025_order_ttj_manzil'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='imtiyoz_nomi',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='order',
            name='kocha',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='order',
            name='telefon',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='order',
            name='tuman',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='order',
            name='viloyat',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
