# Generated by Django 4.2.2 on 2023-07-10 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='fakultet',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
