# Generated by Django 4.2.2 on 2023-07-03 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_foydalanuvchi'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Foydalanuvchi',
        ),
        migrations.AlterField(
            model_name='user',
            name='dekanat',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='super',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='talaba',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
