
// Example starter JavaScript for disabling form submissions if there are invalid fields
(() => {
    'use strict'
    // Fetch all the forms we want to apply custom Bootstrap validation styles to
    const forms = document.querySelectorAll('.needs-validation')
    
    // Loop over them and prevent submission
    Array.from(forms).forEach(form => {
        form.addEventListener('submit', event => {
            if (!form.checkValidity()) {
                event.preventDefault()
                event.stopPropagation()
            }            
            form.classList.add('was-validated')
        }, false)
    })
})()

// FAKULTET
const fakultetName = {
    "Fizika va matematika": [
        "Matematika va informatika", 
        "Matematika o'qitish metodikasi", 
        "Fizika va astronomiya", 
        "Fizika va astronomiya o'qitish metodikasi"
    ],
    "Pedagogika": [
        "Pedagogika va psixologiya", 
        "Psixologiya(amaliy psixologiya)", 
        "Maxsus pedagogika(logopediya)", 
        "Defektologiya(surdopedagogika)", 
        "Defektologiya(oligofrenopedagogika)", 
        "Defektologiya(Logopediya)"
    ],
    "Tarix": [
        "Tarix",
        "Tarix o'qitish metodikasi",
        "Milliy g'oya ma'naviyat asoslari va huquq ta'limi"
    ],
    "Milliy hunarmandchilik va amaliy san'at" : [
        "Musiqa ta'limi",
        "Tasviriy san'at va muhandislik grafikasi",
        "Texnologik ta'lim"
    ],
    "Rus tili va adabiyoti": [
        "Ona tili va adabiyoti(rus tili va adabiyoti)",
        "O'zga tilli guruhlarda rus tili",
        "Ona tili va adabiyoti(rus tili va adabiyoti(o'zga tilli guruhlarda))",
    ],
    "Tabiiy fanlar": [
        "Kimyo",
        "Kimyo o'qitish metodikasi",
        "Biologiya",
        "Biologiya o'qitish metodikasi",
        "Geografiya va iqtisodiy bilim asoslari",
        "Geografiya o'qitish metodikasi"
    ],
    "Xorijiy tillar": [
        "Xorijiy til va adabiyoti(ingliz tili)",
        "Maktabgacha va boshlang'ich ta'limda xorijiy til(ingliz tili)"
    ],
    "O'zbek tili va adabiyoti": [
        "O'zbek tili va adabiyoti"
    ],
    "Maktabgacha ta'lim": [
        "Maktabgacha ta'lim",
        "Maktabgacha ta'lim psixologiyasi va pedagogikasi",
        "Maktab menejmenti"
    ],
    "Boshlang'ich ta'lim": [
        "Boshlang'ich ta'lim",
        "Boshlang'ich ta'lim va sport tarbiyaviy ish"
    ],
    "Jismoniy madaniyat": [
        "Jismoniy madaniyat"
    ]
}



// REGION 
const regionStateInfo = {
    "Qoraqalpog'iston Respublikasi": {
        "Amudaryo tumani": [
            "Jumurtov",
            "Kipshak",
            "Kilichboy",
            "Xitoy"
        ],
        "Beruniy tumani": [
            "Beruniy",
            "Bulish"
        ],
        "Kegayli tumani": [
            "Xalqobod",
            "Kegeyli"
        ],
        "Qonliko'l tumani": [
            "Qanliko'l"
        ],
        "Qorao'zak tumani": [
            "Qorao'zak",
            "Qo'ng'irot",
            "Jasliq",
            "Qaraqalpaqstan",
            "Qiriqqiz",
            "Oltinko'l",
            "Yelabad"
        ],
        "Qo'ng'irot tumani": [],
        "Mo'ynoq tumani": [
            "Mo'ynoq"
        ],
        "Nukus tumani": [
            "Oqmang'it"
        ],
        "Nukus shahri": [
            "Karatau"
        ],
        "Taxtako'pir tumani": [
            "Taxtako'pir"
        ],
        "To'rtko'l tumani": [
            "To'rtko'l",
            "Miskin",
            "Turkmankuli",
            "Tozabog'",
            "Nurli yo'l",
            "Amirobod"
        ],
        "Xo'jayli tumani": [
            "Xo'jayli",
            "Vodnik"
        ],
        "Chimboy tumani": [
            "Chimboy",
            "Ayteke"
        ],
        "Shumanay tumani": [
            "Shumanay"
        ],
        "Ellikqal'a tumani": [
            "Bo'ston",
            "Saxtiyon"
        ],
        "Taxiatosh shahri": [
            "Taxiatosh",
            "Naymanko'l"
        ],
        "Bo'zatov tumani": [
            "Aspantay",
            "Yerkindarya",
            "Ko'k-suv",
            "Qusqanatov"
        ]
    },
    "Andijon viloyati": {
        "Andijon shahri": [],
        "Andijon tumani": [
            "Ayrilish",
            "Butaqora",
            "Bo'taqora",
            "Guliston",
            "Gulobod",
            "Gumbaz",
            "Yorboshi",
            "Zavroq",
            "Kuyganyor",
            "Kunji",
            "Qoraqalpoq",
            "Qo'nji",
            "Qo'shariq",
            "Nayman",
            "Namuna",
            "Og'ullik",
            "Oq-yor",
            "Oq-yor",
            "Orol",
            "Rovvot",
            "Xakan",
            "Xartum",
            "Xartum",
            "Xrabek",
            "Chilon",
            "Chumbog'ich",
            "Ekin tikin",
            "Yangiobod"
        ],
        "Asaka tumani": [
            "Asaka",
            "Zarbdor",
            "Ilg'or",
            "Kujgan",
            "Kujgan",
            "Qadim",
            "Qoratepa",
            "Mustahkam\r\n\r\nMustahkam\r\nMustahkam",
            "Navkan",
            "Niyozbotir",
            "Oqbo'yra",
            "T.Aliyev",
            "O'zbekiston"
        ],
        "Baliqchi tumani": [
            "Baliqchi",
            "Baliqchi",
            "Bo'ston",
            "Guliston",
            "Olimbek",
            "Oxunboboyev nomli",
            "Siza",
            "O'rmonbek",
            "Xo'jaobod",
            "Xo'jaobod",
            "Chinobod markaz",
            "Eskixaqqulobod"
        ],
        "Buloqboshi tumani": [
            "Andijon",
            "Buloqboshi",
            "Buloqboshi",
            "Kulla",
            "Mayariq",
            "Nayman",
            "Uchtepa",
            "Shirmonbuloq",
            "Shirmonbuloq"
        ],
        "Bo'z tumani": [
            "Bo'z",
            "M.Jalolov nomli",
            "M.Jalolov nomli",
            "Xovos",
            "Xoldevonbek",
            "Xoldevonbek"
        ],
        "Jalaquduq tumani": [
            "Abdullabiy",
            "Beshtal",
            "Beshtol",
            "Guliston",
            "Yorqishloq",
            "Yorqishloq",
            "Jalaquduq",
            "Jalaquduq",
            "Jalolquduq",
            "Janubiy olamushuk",
            "Ko'kalam",
            "Qatortol",
            "Qo'shtepa",
            "Oyim",
            "Teshiktosh"
        ],
        "Izbosgan tumani": [
            "Gurkirov",
            "Izboskan",
            "Maygir",
            "Maygir",
            "Namuna",
            "Paytug",
            "To'rtko'l",
            "Uzun ko'cha",
            "O'rtoqlar",
            "Shermatobod",
            "Erkin",
            "Yakkatut",
            "Yangi qishloq",
            "Yangizamon"
        ],
        "Qorasuv shahri": [],
        "Qo'rg'ontepa tumani": [
            "Dardok",
            "Qorasuv",
            "Qo'rg'ontepa",
            "Qo'rg'ontepa",
            "Savay",
            "Sultonobod",
            "Sultonobod",
            "Chimyon"
        ],
        "Marhamat tumani": [
            "Boboxuroson",
            "Ko'tarma",
            "Ko'tarma",
            "Qorabog'ish",
            "Qorabog'ish",
            "Qoraqo'rg'on",
            "Qoraqo'rg'on",
            "Marxamat",
            "Marxamat",
            "Marxamat",
            "Polvontosh",
            "Rovot",
            "O'qchi",
            "Xakka",
            "Xo'jaariq",
            "Shukurmergan"
        ],
        "Oltinko'l tumani": [
            "Bo'ston",
            "Dalvarzin",
            "Jalabek",
            "Jalabek",
            "Ijtimoiyat",
            "Kumakay",
            "Kumakay",
            "Qo'shtepa",
            "Qo'shtepasaroy",
            "Madaniy mehnat",
            "Markaz",
            "Maslahat",
            "Maslahat",
            "Namuna",
            "Oltinko'l",
            "Oraziy",
            "Oxunboboyev nomli",
            "Suvyulduz",
            "Xondibog'i"
        ],
        "Paxtaobod tumani": [
            "Bo'ston",
            "Do'stlik",
            "Izboskan",
            "Ittifoq",
            "Madaniyat",
            "Paxtakor",
            "Paxtaobod",
            "Pushmon",
            "Uyg'ur"
        ],
        "Ulug'nor tumani": [
            "Mingbuloq",
            "Mingchinor",
            "Navoiy nomli",
            "Oq oltin",
            "Oq oltin"
        ],
        "Xonabod tumani": [
            "Xonobod",
            "Xonobod"
        ],
        "Xo'jaobod tumani": [
            "Birlashgan",
            "Guliston",
            "Dilkushod",
            "Ko'tarma",
            "Manak",
            "Manak",
            "Oltin vodiy",
            "Xidirsha",
            "Xo'jaobod",
            "Xo'jaobod"
        ],
        "Shahrixon tumani": [
            "Abdubiy",
            "Vaxim",
            "Guliston",
            "Nazarmaxram",
            "Naynavo",
            "Paxtaobod",
            "Segaza kum",
            "Toshtepa",
            "O'zbekiston",
            "O'rta Shaxrixon",
            "Xaqiqat",
            "Cho'ja",
            "Cho'ja",
            "Shaxrixon",
            "Yuqori Shaxrixon",
            "Yangi yo'l"
        ],
        "Asaka shahri": []
    },
    "Buxoro viloyati": {
        "Buxoro shahri": [],
        "Buxoro tumani": [
            "Arabxona",
            "Bog'ikalon",
            "Gala Osiyo",
            "Gulshanobod",
            "Dexcha",
            "Istiqbol",
            "Kunjiqal?a",
            "Ko'chko'mar",
            "Qavola Maxmud",
            "Podshoyi",
            "Rabotak",
            "Rabotiqalmoq",
            "Saxovat",
            "Sohibkor",
            "So'fikorgar",
            "O'rta Novmetan",
            "Xumini bolo",
            "Shergiron",
            "Shexoncha",
            "Yangi Turmush",
            "Yangiobod"
        ],
        "Vobkent tumani": [
            "Vobkent",
            "Imomqazixon",
            "Kosari",
            "Kumushkent",
            "Qipchoq",
            "Qo'ng'irot",
            "Navbahor",
            "Pirmast",
            "Roxkent",
            "Xayrobotcha",
            "Xayrxush",
            "Xalach",
            "Shirin",
            "Exson",
            "Yangikent"
        ],
        "G'ijduvon tumani": [
            "Abadi",
            "Armechan",
            "Beshtuvo",
            "Buktaroy",
            "G.Yunusov nomli",
            "Gajdumak",
            "G'ijduvon",
            "G'ovshun",
            "Dodarak",
            "Jovgari",
            "Zarangari",
            "Ko'kcha",
            "Ko'lijabbor",
            "Qaraxoni",
            "Mazragan",
            "Namatgaron",
            "Paxtaobod",
            "Pozagari",
            "Sarvari",
            "Sarmijon",
            "Soktari",
            "O'zanon",
            "Ulfatbibi",
            "Firishkent",
            "Xatcha",
            "Chag'dari",
            "Yuqori Qumoq",
            "Yuqori Rostgo'y"
        ],
        "Jondor tumani": [
            "Aleli",
            "Dalmun",
            "Dalmun",
            "Jondor",
            "Zarafshon",
            "Ko'liyon",
            "Qaroli",
            "Lolo",
            "Mirzayon",
            "Mustaqillik",
            "Oxshix",
            "Paxlavon",
            "Po'loti",
            "Romish",
            "Samonchuq",
            "Samonchuq",
            "Tobagar",
            "Ushot",
            "Xazorman",
            "Xumdonak",
            "Xumini bolo"
        ],
        "Kogon tumani": [
            "Chorzona",
            "B.Naqshband",
            "Beklar",
            "Guliston",
            "Kogon",
            "Niyozhoji",
            "Nurafshon",
            "Sarayon",
            "Sarayonobod",
            "Tutikunda",
            "Xo'ja Yakshaba",
            "Yangi xayot"
        ],
        "Kogon shahri": [],
        "Qorako'l tumani": [
            "Bandboshi",
            "Bandboshi",
            "Darg'abog'i",
            "Darg'ali",
            "Jig'achi",
            "Jig'achi",
            "Ziyorat",
            "Kulonchi",
            "Qozon",
            "Qorako'l",
            "Qorako'l",
            "Qoraun",
            "Qorahoji",
            "Qorahoji",
            "Quvvacha",
            "Quvvacha",
            "Quyi Yangibozor",
            "Mallaishayx",
            "Mirzaqal?a",
            "Sayyod",
            "Sayyot",
            "Solur",
            "Chandir",
            "Chandirobod",
            "Chovli",
            "Sho'rabot",
            "Sho'rrabot",
            "Yakka A?lam",
            "Yangiqal?a"
        ],
        "Qorovulbozor tumani": [
            "Buzachi",
            "Bo'ston",
            "Jarqoq",
            "Qorovulbozor",
            "Navbahor"
        ],
        "Olot tumani": [
            "Bahoriston",
            "Bo'ribek Chandir",
            "Ganchi Chandir",
            "Guliston",
            "Denov",
            "Jayxunobod",
            "Jumabozor",
            "Kesakli",
            "Qirlishon",
            "Qirtay",
            "Olot",
            "Paxtakor",
            "Soyin-qorovul",
            "Sola qorovul",
            "Talqon-sayyot",
            "O'zbekiston",
            "Chandir",
            "Chovdur",
            "Chorbog'"
        ],
        "Peshku tumani": [
            "Bog'imuso",
            "Varaxsho",
            "Jonkeldi",
            "Zandani",
            "Ibn Sino nomli",
            "Qal?ai Mirishkor",
            "Qoraqalpoq",
            "Mahallai-Mirishkor",
            "Peshku",
            "Peshku",
            "Chibog'oni",
            "Shavgon",
            "Yangibozor",
            "Yangibozor"
        ],
        "Romitan tumani": [
            "Bog'iturkon",
            "Gazli",
            "Qizil Ravot",
            "Qoqishtuvon",
            "Qo'rg'on",
            "Romitan",
            "Romitan",
            "Xosa",
            "Chelong'u",
            "Sho'rcha",
            "Yuqori G'azberon"
        ],
        "Shofirkon tumani": [
            "Bog'iafzal",
            "Vargonze",
            "G'ulomte",
            "Denov",
            "Do'rmon",
            "Jo'ynav",
            "Jo'yrabot",
            "Jo'yrabot",
            "Iskogare",
            "Iskogare",
            "Quyi Chuqurak",
            "Mazlaxon chandir",
            "Mirzoqul",
            "Savrak",
            "Sulton Jo'ra",
            "Talisafed",
            "Tezguzar",
            "Undare",
            "Chandir",
            "Sh.Hamroyev nomli",
            "Shofirkon"
        ]
    },
    "Jizzax viloyati": {
        "Arnasoy tumani": [
            "Bo'ston",
            "Gulbahor",
            "G'oliblar",
            "Do'stlik",
            "Zarafshon",
            "Oltin vodiy",
            "Cho'lquvar",
            "Yangibo'ston"
        ],
        "Baxmal tumani": [
            "Alamli",
            "Barlos",
            "Baxmal",
            "Baxmal",
            "Bog'ishamol",
            "Gulbuloq",
            "Mo'g'ol",
            "Mo'g'ol",
            "Novqa",
            "Oyqor",
            "Oqtosh",
            "Oqtosh",
            "Sangzor",
            "Tongotar",
            "Tongotar",
            "Uzunbuloq",
            "O'smat"
        ],
        "G'allaorol tumani": [
            "Abdukarim",
            "Buloqboshi",
            "Guliston",
            "Gulchambar",
            "G'allaorol",
            "G'ubdin",
            "Ittifoq",
            "Korizquduq",
            "Ko'kbuloq",
            "Qangliobod",
            "Qipchoqsuv",
            "Qo'ytosh",
            "Lalmikor",
            "Madaniyat",
            "Marjonbuloq",
            "Mirzabuloq",
            "Moltob",
            "Mulkush",
            "Tozaurug'",
            "Xonimqo'rg'on",
            "Chuvilloq"
        ],
        "Do'stlik tumani": [
            "Bog'zor",
            "Bunyodkor",
            "Do'stlik",
            "Qahramon",
            "Manas",
            "Mevazor",
            "Navro'z",
            "Oltin vodiy",
            "Saritepa"
        ],
        "Sh.Rashidov tumani": [
            "Gandumtosh",
            "Jizzaxlik",
            "Ziyokor",
            "Kuyovboshi",
            "Qang'li",
            "Qang'li",
            "Qorayantoq",
            "Qulama",
            "Qo'shbarmoq",
            "Mulkanlik",
            "Oq oltin",
            "Paxtaobod",
            "Rovat",
            "Samarqand quduq",
            "Toqchiliq",
            "Uch-tepa",
            "Uchtepa",
            "Fayzobod",
            "Xayrobod"
        ],
        "Jizzax shahri": [],
        "Zarbdor tumani": [
            "Adirobod",
            "Andijon",
            "Bo'ston",
            "Zarbdor",
            "Lalmikor",
            "Oqar",
            "Tinchlik",
            "Toshkesgan",
            "Fayzobod",
            "Sharq yulduzi",
            "Sharq yulduzi",
            "Yangikent"
        ],
        "Zafarobod tumani": [
            "Birlik",
            "Yorqin",
            "Yorqin",
            "Zafarobod",
            "Lolazor",
            "Nurafshon",
            "Pistalikent",
            "Uzun",
            "Xulkar",
            "Chimqo'rg'on"
        ],
        "Zomin tumani": [
            "A.Navoiy",
            "Beshkubi",
            "Gulshan",
            "G'allakor",
            "Dashtobod",
            "Duoba",
            "Yom",
            "Zomin",
            "Istiqlol",
            "Obi hayot",
            "Pshag'or",
            "Sirg'ali",
            "Chorvador",
            "Shirin"
        ],
        "Mirzacho'l tumani": [
            "Bog'bon",
            "Gagarin",
            "Gulzor",
            "Jibek-jo'li",
            "Mirzadala",
            "Paxtazor",
            "Toshkent",
            "O'zbekiston",
            "Yangidala"
        ],
        "Paxtakor tumani": [
            "Bog'ishamol",
            "Buyuk Ipak yo'li",
            "Gulzor",
            "Mingchinor",
            "Oq buloq",
            "Olmazor",
            "Paxtakor",
            "Paxtakor",
            "Chamanzor"
        ],
        "Forish tumani": [
            "Arnasoy",
            "Bog'don",
            "Garasha",
            "Darvoza",
            "Qizilqum",
            "Qoraabdol",
            "Omonkeldi",
            "Osmonsoy",
            "Uxum",
            "Uchquloch",
            "Forish",
            "Egizbuloq"
        ],
        "Yangiobod tumani": [
            "Savot",
            "Savot",
            "Sarmich",
            "Xovos",
            "Xo'jamushkent",
            "Havotog'",
            "Yangiobod"
        ]
    },
    "Qashqadaryo viloyati": {
        "G'uzor tumani": [
            "Batosh",
            "Bo'ston",
            "Guliston",
            "Gulshan",
            "G'uzor",
            "Jarariq",
            "Zarbdor",
            "Qorako'l",
            "Qo'shtepa",
            "Mash?al",
            "Mehnatobod",
            "Obihayot",
            "Pachkamar",
            "Xalqabod",
            "Shakarbuloq",
            "Sherali",
            "Sherali",
            "Yangikent"
        ],
        "Dehqonobod tumani": [
            "Beshbuloq",
            "Beshqo'ton",
            "Bibiqorasoch",
            "Bozortepa",
            "Boshchorbog'",
            "Dehqonobod",
            "Duob",
            "Karashina",
            "Qizilcha",
            "Qirqquloch",
            "Qo'rg'ontosh",
            "Obiravon",
            "Oqirtma",
            "Oqqishloq",
            "Oqrabod",
            "Oqtosh",
            "O'zbekiston"
        ],
        "Qamashi tumani": [
            "Badahshon",
            "Balandchayla",
            "Yortepa",
            "Jonbo'zsoy",
            "Ko'kbuloq",
            "Qamay",
            "Qamashi",
            "Qiziltepa",
            "Qiziltepa",
            "Qorabog'",
            "Qoratepa",
            "Qoratepa",
            "Loyqasoy",
            "Rabod",
            "Sarbozor",
            "To'qboy",
            "Chim"
        ],
        "Qarshi tumani": [
            "Beshkent",
            "Bog'obod",
            "G'ubdin",
            "Dasht",
            "Yertepa",
            "Yertepa",
            "Jumabozor",
            "Kat",
            "Kuchkak",
            "Qovchin",
            "Qovchin",
            "Qoratepa",
            "Lag'mon",
            "Mirmiron",
            "Mustaqillik",
            "Navbahor",
            "Navro'z",
            "Nuqrabod",
            "Paxtakor",
            "Poshton",
            "Saroy",
            "Tallikuron",
            "O'zbekiston mustaqilligi",
            "Fayzobod",
            "Xonobod",
            "Hilol",
            "Chaman",
            "Charag'il",
            "Cho'libo'ston",
            "Shilvi",
            "Yangi xayot"
        ],
        "Qarshi shahri": [],
        "Kasbi tumani": [
            "G'alaba",
            "Denov",
            "Denov",
            "Do'stlik",
            "Kasbi",
            "Komilon",
            "Qamashi",
            "Qatag'an",
            "Qatag'on",
            "Qoraqo'ng'irot",
            "Maymanoq",
            "Mug'lon",
            "Mug'lon",
            "Paxtakor",
            "Fazli",
            "Xo'jakasbi",
            "Cho'lquvar",
            "Yuksalish",
            "Yangi qishloq"
        ],
        "Kitob tumani": [
            "Alaqo'yliq",
            "Baxtdarvozasi",
            "Bektemir",
            "Bektemir",
            "Beshterak",
            "Beshterak",
            "Bog'bon",
            "Varganza",
            "Jilisuv",
            "Kitob",
            "Qaynarbuloq",
            "Qatorbog'",
            "Qo'yioqboy",
            "Makrid",
            "Obikanda",
            "Panji",
            "Paxtaobod",
            "Rus qishloq",
            "Sariosiyo",
            "Sevaz",
            "Sevaz",
            "Tagob",
            "Tupchoq",
            "Xoji",
            "Yakkatut",
            "Yangiobod"
        ],
        "Koson tumani": [
            "Alachabob",
            "Boyg'undi",
            "Boyterak",
            "Guvalak",
            "Gulbog'",
            "Gulobod",
            "Do'stlik",
            "Istiqlol",
            "Istiqlol",
            "Koson",
            "Koson",
            "Qo'yi Obron",
            "Qo'ng'irtog'",
            "Mudin",
            "Obod",
            "Oqtepa",
            "Pudina",
            "Po'lati",
            "Rahimso'fi",
            "Rudaksoy",
            "Surhon",
            "Tinchlik",
            "To'lg'a",
            "Esaboy"
        ],
        "Mirishkor tumani": [
            "Bo'ston",
            "Vori",
            "Guliston",
            "Gulshanbog'",
            "Jeynov",
            "Jeynov",
            "Mirishkor",
            "Navbahor",
            "Obod",
            "Pomuq",
            "Pomuq",
            "Chamanzor",
            "Chandir",
            "Yangi Mirishkor",
            "Yangiobod"
        ],
        "Muborak tumani": [
            "Baxt",
            "Diyonat",
            "Qarliq",
            "Qarliq",
            "Qoraqum",
            "Qoraqum",
            "Muborak",
            "Muborak",
            "Sariq",
            "Shayx"
        ],
        "Nishon tumani": [
            "Balxiyak",
            "Guliston",
            "Qirqquloch",
            "Navro'z",
            "Nishon",
            "Nishon",
            "Nuriston",
            "Oydin",
            "Oydinlik",
            "Oq oltin",
            "Oq oltin",
            "Paxtazor",
            "Paxtaobod",
            "Paxtachi",
            "Samarqand",
            "Sardoba",
            "Talimarjon",
            "Shirinobod",
            "Yangi Nishon"
        ],
        "Chiroqchi tumani": [
            "Ayritom",
            "Dam",
            "Dodiq",
            "Jar",
            "Jar",
            "Ko'kdala",
            "Ko'kdala",
            "Qalqama",
            "Qahramon",
            "Qumdaryo",
            "Langar",
            "Mirzato'p",
            "Nurafshon",
            "Olmazor",
            "Pakandi",
            "Paxtaobod",
            "Paxtaobod",
            "Taraqqiyot",
            "Torjilg'a",
            "Uymovut",
            "O'ymovut",
            "Uyshun",
            "Xumo",
            "Chiroqchi",
            "Chiyal",
            "Chiyal",
            "Sho'rquduq",
            "Eski Anxor",
            "Yangihayot"
        ],
        "Shahrisabz tumani": [
            "Ammog'on-1",
            "Anday",
            "Do'xchi",
            "Keldihayot",
            "Kunchiqar",
            "Qumqishloq",
            "Qutchi",
            "Qutchi",
            "Qo'shqanot",
            "Miraki",
            "Mo'minobod",
            "Namaton",
            "Oq suv",
            "Temirchi",
            "To'damaydon",
            "O'zbekiston",
            "O'rtaqo'rg'on",
            "Xitoy",
            "Xo'jaxuroson",
            "Hisorak",
            "Chorshanbe",
            "Shakarteri",
            "Shamaton",
            "Shamaton",
            "Yangiqishloq"
        ],
        "Yakkabog' tumani": [
            "Alako'ylak",
            "Alaqarg'a",
            "Jarqirg'iz",
            "Kattabog'",
            "Qayrag'och",
            "Qayrag'och",
            "Qatag'on",
            "Qishliq",
            "Qo'shchinor",
            "Madaniyat",
            "Mevazor",
            "Samoq",
            "Samoq",
            "Sandal",
            "Turon",
            "O'z",
            "O'rta",
            "Hiyobon",
            "Chaydori",
            "Chubron",
            "Edilbek",
            "Esat",
            "Eski Yakkabog'",
            "Yakkabog'"
        ],
        "Shahrisabz shahri": [],
        "Ko'kdala tumani": [
            "Yettitom",
            "Chiyal",
            "Ko'kdala",
            "Ayritom"
        ]
    },
    "Navoiy viloyati": {
        "Zarafshon shahri": [
            "Nuruntau"
        ],
        "Karmana tumani": [
            "Do'rmon",
            "Yoshlik",
            "Jaloyir",
            "Kamolot",
            "Karmana",
            "Malikrabot",
            "Narpay",
            "Paxtaobod",
            "Podkoron",
            "Uyrot",
            "Xazora",
            "Yangiariq"
        ],
        "Qiziltepa tumani": [
            "Arabon",
            "Baland G'ardiyon",
            "Bo'ston",
            "Vang'ozi",
            "Vang'ozi",
            "G'amxo'r",
            "G'ardiyon",
            "G'oyibon",
            "Zarmetan",
            "Zarmitan",
            "Qalayn-Azizon",
            "Qiziltepa",
            "Oq oltin",
            "Oq soch",
            "Oqmachit",
            "Uzilishkent",
            "O'rtaqo'rg'on",
            "Xo'ja-Hasan",
            "Xo'jaqo'rg'on",
            "Husbuddin",
            "Yangi Hayot"
        ],
        "Konimex tumani": [
            "Balaqaraq",
            "Boymurot",
            "Zafarobod",
            "Karakata",
            "Konimex",
            "Mamiqchi",
            "Sarajal",
            "Uchtobe",
            "Chordara",
            "Sho'rtepa",
            "Yangig'ozg'on",
            "Yangiobod"
        ],
        "Navbahor tumani": [
            "Arabsaroy",
            "Beshrabot",
            "Ijant",
            "Kalkonota",
            "Keskanterak",
            "Keskanterak",
            "Quyi Beshrabot",
            "Olchin",
            "Saroy",
            "Turkiston",
            "Yangi-yo'l",
            "Yangiqo'rg'on"
        ],
        "Navoiy shahri": [
            "Tinchlik"
        ],
        "Nurota tumani": [
            "Gum",
            "G'ozg'on",
            "Dehibaland",
            "Qizilcha",
            "Qizilcha",
            "Nurota",
            "Nurota",
            "Sentob",
            "Temurqovuq",
            "Chuya",
            "Chuya",
            "Yangibino"
        ],
        "Tomdi tumani": [
            "Ayaqquduq",
            "Keregetau",
            "Keriz",
            "Oktau",
            "Suketti",
            "Tomdibuloq",
            "Tomdibuloq",
            "Shiyeli"
        ],
        "Uchquduq tumani": [
            "Altintov",
            "Bozdun",
            "Ko'kayaz",
            "Mingbuloq",
            "Shalxar",
            "Uchquduq",
            "Uzunquduq"
        ],
        "Xatirchi tumani": [
            "Bog'chakalon",
            "Bog'ishamol",
            "G'alabek",
            "Jaloyir",
            "Ko'ksaroy",
            "Langar",
            "O'zbekiston",
            "Olchinobod",
            "Paxtakor",
            "Polvontepa",
            "Pulkan shoir",
            "Qo'rg'on",
            "Qo'shchinor",
            "Qoracha",
            "Sahovat",
            "Tasmachi",
            "Turkman",
            "Xonaqa",
            "Yangi qurilish",
            "Yangirabod",
            "Yangirabod"
        ],
        "G'ozg'on shahri": []
    },
    "Namangan viloyati": {
        "Kosonsoy tumani": [
            "Bog'ishamol",
            "Chindavul",
            "Chindovul",
            "Chust ko'cha",
            "Istiqlol",
            "Koson",
            "Koson",
            "Kosonsoy",
            "Ozod",
            "Qorasuv",
            "Ququmboy",
            "Ququmboy",
            "Shirin",
            "Tergachi",
            "Tergachi",
            "Yangi shahar",
            "Yangiyo'l",
            "Yoshlik",
            "Yangishahar"
        ],
        "Mingbuloq tumani": [
            "Bo'ston",
            "Dovduq",
            "Dovduq",
            "Go'rtepa",
            "Go'rtepa",
            "Gulbog'",
            "Jo'masho'y",
            "Kugolikul",
            "Madyarovul",
            "Mehnatobod",
            "Mehnatobod",
            "Momoxon",
            "O'zgarish",
            "Oltinko'l"
        ],
        "Namangan tumani": [
            "Bog'ishamol",
            "Istiqlol",
            "Mirishkor",
            "Mirishkor",
            "Navbahor",
            "Navbahor",
            "Nurafshon",
            "O'zbekiston",
            "Qumqo'rg'on",
            "Qumqo'rg'on",
            "Sho'rqishloq",
            "Sho'rqo'rg'on",
            "Tepaqo'rg'on",
            "Toshbuloq",
            "Xonabod"
        ],
        "Namangan shahri": [
            "Davlatobod tumani",
            "Namangan shahrining tumanlari",
            "Yangi Namangan tumani"
        ],
        "Norin tumani": [
            "Chambil",
            "Marg'izor",
            "Marg'uzar",
            "Norinkapa",
            "Norinkapa",
            "Pastki cho'ja",
            "Paxtaqishloq",
            "Qo'rg'ontepa",
            "Qorateri",
            "Sho'ra",
            "To'da",
            "Toshloq",
            "Uchtepa",
            "Uchtepa",
            "Xaqqulobod",
            "Xo'jaobod",
            "Xo'jaobod"
        ],
        "Pop tumani": [
            "Chodak",
            "Chodak",
            "Chorkesar",
            "Chorkesar-2",
            "G'urumsaroy",
            "G'urumsaroy",
            "Madaniyat",
            "Madaniyat",
            "Navbahor",
            "Nayman",
            "Oltinkon",
            "Paxtaobod",
            "Pop",
            "Pop",
            "Pungon",
            "Pungon",
            "Qandig'on",
            "Qurg'onobod",
            "Sang",
            "Sirdaryo",
            "Uyg'ur",
            "Uyg'ur",
            "Uyg'ursoy",
            "Xalqobod",
            "Yangi hayot",
            "Yangi Xo'jaobod"
        ],
        "To'raqo'rg'on tumani": [
            "Axsi",
            "Axsi",
            "Buramatut",
            "Buramatut",
            "Kalvak",
            "Katagansaroy",
            "Katagon",
            "Kichikqurama",
            "Mozorko'xna",
            "Namdon",
            "Olchin",
            "Oqtosh",
            "Saroy",
            "Sayram",
            "Shaxand",
            "Shaxand",
            "To'raqo'rg'on",
            "Xo'jand",
            "Yandama",
            "Yandama",
            "Yettikon",
            "Yortepa"
        ],
        "Uychi tumani": [
            "Axsi",
            "Birlashgan",
            "Birlashgan",
            "Boyog'on",
            "Churtuk",
            "Fayziobod",
            "G'ayrat",
            "G'ayrat",
            "Jiydakapa",
            "Jiydakapa",
            "Kichik toshloq",
            "Mashad",
            "Mashad",
            "O'nxayat",
            "Soku",
            "Teshiktosh",
            "Uychi",
            "Uychi",
            "Yorkatay",
            "Yorqo'rg'on",
            "Ziyokor"
        ],
        "Uchqo'rg'on tumani": [
            "Baxt",
            "O'zbekiston",
            "Qayqi",
            "Qayqi",
            "Qo'g'ay",
            "Qo'g'ay",
            "Qo'g'ay-o'lmas",
            "Uchqo'rg'on",
            "Uchyog'och",
            "Yangi yor",
            "Yangiobod",
            "Yangiobod",
            "Yashiq"
        ],
        "Chortoq tumani": [
            "Alixon",
            "Alixon",
            "Ayqiron",
            "Ayqiron",
            "Baliqli ko'l",
            "Bog'iston",
            "Chortoq",
            "Karaskan",
            "Ko'shan",
            "Koroskon",
            "Muchum",
            "Muchum",
            "Ora ariq",
            "Pastki Peshqo'rg'on",
            "Peshqo'rg'on",
            "Saroy",
            "Tinchlik",
            "Xazratishox",
            "Xazratishox",
            "Yuqori Peshqo'rg'on"
        ],
        "Chust tumani": [
            "Axcha",
            "Axcha",
            "Baymoq",
            "Chust",
            "G'ova",
            "G'ova",
            "Karkidon",
            "Karkidon",
            "Karnon",
            "Karnon",
            "Og'asaray",
            "Olmos",
            "Olmos",
            "Qoraqo'rg'on",
            "Sarimsoqtepa",
            "Sho'rkent",
            "Shoyon",
            "Shoyon",
            "Varzik",
            "Varzik",
            "Xisorak",
            "Xisorak",
            "Yorqishloq"
        ],
        "Yangiqo'rg'on tumani": [
            "Bekobod",
            "Bekobod",
            "Birlashkan",
            "G'ovazon",
            "Iskavot",
            "Istiqlol",
            "Kalisho",
            "Ko'kyor",
            "Nanay",
            "Nanay",
            "Navkent",
            "Navkent",
            "Navro'zobod",
            "Poromon",
            "Poromon",
            "Qizil qiyoq",
            "Qorachasho'rkent",
            "Qorapolvon",
            "Qorapolvon",
            "Qorayong'oq",
            "Rovot",
            "Salmon",
            "Sangiston",
            "Sharq yulduzi",
            "Xo'jasho'rkent",
            "Yangiqo'rg'on",
            "Yumaloqtepa",
            "Zarbdor",
            "Zarkent",
            "Zarkent"
        ],
        "Davlatobod tumani": []
    },
    "Samarqand viloyati": {
        "Bulung'ur tumani": [
            "Beshqo'ton",
            "Bog'bon",
            "Bulung'ur",
            "F.Yo'ldoshev nomli",
            "Kildon",
            "Kildon",
            "Kulchabiy",
            "Navoiy nomli",
            "O'rtabuloq",
            "Soxibkor",
            "Soxibkor"
        ],
        "Jomboy tumani": [
            "Dehqonobod",
            "Dehqonobod",
            "Eski Jomboy",
            "G'azira",
            "Jomboy",
            "Jomboy",
            "Juriyat",
            "Kattaqishloq",
            "Qangli",
            "Qo'ng'irot",
            "Qoramuyin",
            "Sherqo'rg'on",
            "Xo'ja",
            "Xolvoyi"
        ],
        "Ishtixon tumani": [
            "Azamat",
            "Azamat",
            "Bahrin",
            "Chordara",
            "Damariq",
            "Fayziobod",
            "Halqabod",
            "Haqiqat",
            "Ishtixon",
            "Mitan",
            "O'rtaqishloq",
            "Odil",
            "Qirqyigit",
            "Qurli",
            "Ravot",
            "Shayxislom",
            "Sheyxlar",
            "Sug'ot",
            "Xalqobod",
            "Yangikent",
            "Yangirabot",
            "Zarband"
        ],
        "Kattaqo'rg'on tumani": [
            "Durbesh",
            "Girdiqo'rg'on",
            "Jumaboy",
            "Kattako'rpa",
            "Kattaming",
            "Kattaming",
            "Kichikmundiyon",
            "Moybuloq",
            "Mundiyon",
            "Omonboy",
            "Payshanba",
            "Polvontepa",
            "Qo'shtepa",
            "Qoradaryo",
            "Saroyqo'rg'on",
            "Suv xovuzi",
            "Vayrat",
            "Yangiqo'rg'oncha",
            "Yangiqo'rg'oncha"
        ],
        "Kattaqo'rg'on shahri": [
            "Ingichka"
        ],
        "Qo'shrabot tumani": [
            "Jush",
            "Oqtepa",
            "Oxunboboyev nomli",
            "Pichat",
            "Qo'shrabot",
            "Qo'shrabot",
            "Urgandji",
            "Zarkent",
            "Zarmitan"
        ],
        "Narpay tumani": [
            "Balandqo'rg'on",
            "Chaqar",
            "Guliston",
            "Islom Shoir",
            "Kosogoron",
            "Mirbozor",
            "Oltio'g'il",
            "Oqtosh",
            "Qadim",
            "Qo'yi Charxin",
            "Qorako'l",
            "Qorasiyrak",
            "Yangirabod"
        ],
        "Nurabod tumani": [
            "Jarquduq",
            "Jom",
            "Nurbuloq",
            "Nurbuloq",
            "Nurobod",
            "Sazog'on",
            "Tim",
            "Tutli",
            "Ulus"
        ],
        "Oqdaryo tumani": [
            "A.Navoiy",
            "Avazali",
            "Bolta",
            "Dahbed",
            "Kumushkent",
            "Loyish",
            "Oqdaryo",
            "Oytamg'ali",
            "Primkent",
            "Qirqdarxon",
            "Qorateri",
            "Yangikent",
            "Yangiobod",
            "Yangiqo'rg'on",
            "Yangiqo'rg'on",
            "Zarafshon"
        ],
        "Payariq tumani": [
            "Birlashgan",
            "Chelak",
            "Choparoshli",
            "Choshtepa",
            "Do'stlarobod",
            "Do'stlik",
            "G'ujumsoy",
            "Guliston",
            "Ko'kdala",
            "Ko'ksaroy",
            "Ko'lto'sin",
            "O'rta saydov",
            "Oqqo'rg'on",
            "Oqqo'rg'on",
            "Oytamg'ali",
            "Payariq",
            "Qorasuv",
            "Qorasuv",
            "Sanoat",
            "Tomoyrat",
            "Tupolos",
            "Xo'ja Ismoil"
        ],
        "Pastarg'om tumani": [
            "Agron",
            "Anxor",
            "Arabxona",
            "Balhiyon",
            "Besh qahramon",
            "Bolatosh",
            "Charxin",
            "Chimboy",
            "Chortut",
            "Dimishkibolo",
            "Do'rmontepa",
            "Go'zalkent",
            "Go'zalkent",
            "Hindiboyi",
            "Iskandari",
            "Jag'alboyli",
            "Juma",
            "Mehnat",
            "Namuna",
            "Nayman",
            "O'rta Charxin",
            "Po'latchi",
            "Sanchikul",
            "Saribosh",
            "Saribosh",
            "Torariq"
        ],
        "Paxtachi tumani": [
            "Do'stobod",
            "Karnab",
            "Misit",
            "Past Burkut",
            "Qodirist",
            "Quyiboq",
            "Sanchiqul",
            "Sultonobod",
            "Suluvqo'rg'on",
            "Urgich",
            "Xayrobod",
            "Xumor",
            "Xumor",
            "Yuqori Po'latchi",
            "Ziyovuddin"
        ],
        "Samarqand tumani": [
            "Bog'ibaland",
            "Dashtakibolo",
            "Gulobod",
            "Kattaqo'rg'onariq",
            "Kulbaipoyon",
            "Ohalik",
            "Qaynama",
            "Qo'shtamg'ali",
            "Ulug'bek",
            "Xo'ja Ahrori Vali"
        ],
        "Samarqand shahri": [
            "Farxod",
            "Kimyogar",
            "Xishrav"
        ],
        "Toyloq tumani": [
            "Adas",
            "Adas",
            "Bog'izag'on",
            "Bog'izag'on",
            "G'o'lba",
            "Jumabozor",
            "Madaniyat",
            "Qo'rg'oncha",
            "Sochakibolo",
            "Tepaqishloq",
            "Toyloq",
            "Toyloq"
        ],
        "Urgut tumani": [
            "Baxrin",
            "Beshbuloq",
            "Buloqboshi",
            "G'o's",
            "G'o's",
            "Ilonli",
            "Ispanza",
            "Ispanza",
            "Jartepa",
            "Jartepa",
            "Kamangaron",
            "Kenagas",
            "Mirzaqishloq",
            "Pochvon",
            "Pochvon",
            "Qoratepa",
            "Uramas",
            "Uramas",
            "Urgut",
            "Yangiariq"
        ]
    },
    "Surxandaryo viloyati": {
        "Angor tumani": [
            "Angor (mavjud)",
            "Angor (yangi)",
            "Gilambob",
            "Do'stlik",
            "Zang",
            "Zartepa",
            "Istiqlol",
            "Kayran",
            "Kayran",
            "Qorasuv",
            "Qorasuv",
            "Navoiy",
            "Novshahar",
            "Tallimaron",
            "Tallimaron",
            "Talloshqon",
            "Xomkon",
            "Yangi turmush",
            "Yangiobod"
        ],
        "Boysun tumani": [
            "Boysun",
            "Ketmonchi",
            "Kofrun",
            "Qorabo'yin",
            "Qo'ng'irot",
            "Qo'rg'oncha",
            "Machay",
            "Pasurxi",
            "Poyonqo'rg'on",
            "Rabot",
            "Tangimush",
            "Temir darvoza",
            "Chinorli"
        ],
        "Denov tumani": [
            "Anbarsoy",
            "Binokor",
            "Dahana",
            "Dahana",
            "Denov",
            "Denov",
            "Do'stlik",
            "Jamatak",
            "Kenagas",
            "Qiziljar",
            "Qiziljar",
            "Namozgoh",
            "Paxtakurash",
            "Pistamozor",
            "Sina",
            "Tortuvli",
            "Farg'ona",
            "Xayrabot",
            "Xitoyan",
            "Xolchayon",
            "Xolchayon",
            "Hazarbog'",
            "Yurchi",
            "Yurchi",
            "Yangi Hazorbog'",
            "Yangibog'",
            "Yangibog'",
            "Yangizamon",
            "Yangiobod",
            "Yangiobod"
        ],
        "Jarqo'rg'on tumani": [
            "Dehqonobod",
            "Jarqo'rg'on",
            "Jarqo'rg'on",
            "Kakaydi",
            "Kafrun",
            "Qoraqursoq",
            "Markaziy Surxon",
            "Minor",
            "Minor",
            "Oqqo'rg'on",
            "Surxon",
            "Chorjo'y",
            "Sharq yulduzi"
        ],
        "Qiziriq tumani": [
            "Bandixon",
            "Zarkamar",
            "Istara",
            "Karmaki",
            "Kirshak",
            "Kunchiqish",
            "Qiziriq",
            "Mehnatobod",
            "Olmazor",
            "Paxtakor",
            "Sariq",
            "Chorvador",
            "Sharq Istara",
            "Yangi yo'l",
            "Yangi hayot"
        ],
        "Qo'mqo'rg'on tumani": [
            "Azlarsoy",
            "Arslonboyli",
            "Bog'ora",
            "Jaloir",
            "Jaloir Qo'rg'oni",
            "Jiydali",
            "Ketmon",
            "Qarsoqli",
            "Qumqo'rg'on",
            "Qumqo'rg'on",
            "Navbahor",
            "Oqjar",
            "Oqqapchig'ay",
            "Oqsoy",
            "Hurriyat",
            "Sheroziy",
            "Elbayon",
            "Elobod",
            "Yuqori Kakaydi",
            "Yangiyer"
        ],
        "Muzrabot tumani": [
            "Baynalmilal",
            "Baxt",
            "Beshqo'ton",
            "Boldir",
            "Guliston",
            "Iftixor",
            "Qozoyoqli",
            "Qorakamar",
            "Muzrabot",
            "Navbahor",
            "Obodon",
            "Ozod Vatan",
            "Oq oltin",
            "Sarhad",
            "Taskent",
            "Xalqobod",
            "Chegarachi",
            "Sharq yulduzi",
            "Sho'rob"
        ],
        "Oltinsoy tumani": [
            "Botosh",
            "Bo'ston",
            "Vaxshivor",
            "Gulobod",
            "Dug'oba",
            "Jobu",
            "Ipoq",
            "Qorliq",
            "Qorliq",
            "Qurama",
            "Lutfiy",
            "Mirshodi",
            "Mormin",
            "Oq oltin",
            "Oqarbuloq",
            "Oltinsoy",
            "Uzumzor",
            "Xayrandara",
            "Xo'jasoat",
            "Chep",
            "Shakarqamish",
            "Ekraz",
            "Yangiqurilish"
        ],
        "Sariosiyo tumani": [
            "Bog'i iram",
            "Bo'yropo'sht",
            "Buyuk kelajak",
            "Dashnobod",
            "Navro'z",
            "Sangardak",
            "Sariosiyo",
            "So'fiyon",
            "Toqchiyon",
            "Tortuli",
            "O'zbekiston",
            "Xufar",
            "Sharg'un",
            "Yangihayot"
        ],
        "Termiz tumani": [],
        "Termiz shahri": [
            "At-Termiziy",
            "Kokildorota",
            "Qizilboy",
            "Limonchi",
            "Mehnatobod",
            "Mustaqillik",
            "Namuna",
            "Pattakesar",
            "Paxtaobod",
            "Tajribakor",
            "Uchqizil",
            "Uchqizil",
            "Chegarachi",
            "Yangiariq"
        ],
        "Uzun tumani": [
            "Bobotog'",
            "Jonchekka",
            "Jonchekka",
            "Qarashiq",
            "Malandiyon",
            "Mehnat",
            "Oq Ostona",
            "Telpakchinor",
            "Uzun",
            "Uzun",
            "Ulanqul",
            "Fayzova",
            "Xonjiza",
            "Chinor",
            "Yangi kuch",
            "Yangi ro'zg'or"
        ],
        "Sherobod tumani": [
            "Bo'ston",
            "Zarabog'",
            "Kilkon",
            "Ko'hitang",
            "Navbog'",
            "Oqqo'rg'on",
            "Paxtaobod",
            "Rabatak",
            "Sariqamish",
            "Sariqamish",
            "Seplon",
            "Talloshqon",
            "Chinobod",
            "Cho'yinchi",
            "Sherobod",
            "Yangiariq",
            "Yangiturmush"
        ],
        "Sho'rchi tumani": [
            "Alpomish",
            "Baxtlitepa",
            "G'armaqo'rg'on",
            "Dalvarzin",
            "Jaloir",
            "Jarqishloq",
            "Joyilma",
            "Karvon",
            "Kattasovur",
            "Qo'ldosh",
            "Qo'shtegirmon",
            "Savur",
            "Sohibkor",
            "To'la",
            "Xushchekka",
            "Sho'rchi",
            "Sho'rchi",
            "Elbayon",
            "Elobod",
            "Yalti",
            "Yangibozor"
        ],
        "Bandixon tumani": [
            "Bandixon"
        ]
    },
    "Sirdaryo viloyati": {
        "Boyovut tumani": [
            "Bekat",
            "Boyovut",
            "Boyovut",
            "Buyuk yurt",
            "G'allakor",
            "Darvazakir",
            "Dehqonobod",
            "Do'stlik",
            "Do'stlik",
            "Laylakko'l",
            "Madaniyat",
            "Markaz",
            "Mingchinor",
            "Olmazor",
            "Tabarruk",
            "Tinchlik"
        ],
        "Guliston tumani": [
            "Beshbuloq",
            "Beshbuloq",
            "Dehqonobod",
            "Zarbdor",
            "Kunchi",
            "Oltin O'rda",
            "Oltintepa",
            "Soyibobod",
            "Soxilobod",
            "Ulug'bek",
            "Xalqako'l",
            "Xumo",
            "Hulkar",
            "Chortoq"
        ],
        "Guliston shahri": [
            "Bahor",
            "Do'stlik",
            "Ulug'obod"
        ],
        "Mirzaobod tumani": [
            "Bahoriston",
            "Birlashgan",
            "Yo'ldoshobod",
            "Mehnatobod",
            "Mirzacho'l",
            "Navbahor",
            "Navro'z",
            "Nurafshon",
            "Oqoltin",
            "Oqoltin",
            "Toshkent"
        ],
        "Oqoltin tumani": [
            "Andijon",
            "Ahillik",
            "Bo'ston",
            "Sardoba",
            "Farg'ona",
            "Shodlik"
        ],
        "Sayxunobod tumani": [
            "Guliston",
            "Istiqlol",
            "Ittifak",
            "Nurota",
            "Paxtakon",
            "Sayxun",
            "Sohil",
            "O'zbekiston",
            "Sho'ro'zak",
            "Sho'ro'zak",
            "Yangi hayot"
        ],
        "Sardoba tumani": [
            "Gulzor",
            "Guliston",
            "Qo'rg'ontepa",
            "Paxtaobod",
            "Cho'lQuvar",
            "Yangiqishloq",
            "Yangiobod"
        ],
        "Sirdaryo tumani": [
            "Baxt",
            "J.Mamanov",
            "Ziyokor",
            "Quyosh",
            "Malik",
            "Malik",
            "Oydin",
            "Paxtazor",
            "Sirdaryo",
            "Sirdaryo",
            "Turon",
            "Xaqiqat",
            "Xalqobod",
            "Cho'lto'qay",
            "Sholikor"
        ],
        "Xavos tumani": [
            "Binokor",
            "Gulbahor",
            "Gulbahor",
            "Zafarobod",
            "Qahramon",
            "Paxtakor",
            "Soxibkor",
            "Turkiston",
            "Farxod",
            "Xovos",
            "Xovotog'",
            "Xusnobod",
            "Chamanzor"
        ],
        "Shirin shahri": [],
        "Yangiyer shahri": []
    },
    "Toshkent viloyati": {
        "Angiren shahri": [
            "Krasnogorsk",
            "Nurobod",
            "Yangiobod"
        ],
        "Bekabod tumani": [
            "Bahoriston",
            "Bekobod",
            "Bobur",
            "Gulzor",
            "Guliston",
            "Dalvarzin",
            "Jumabozor",
            "Zafar",
            "Ko'rkam",
            "Qiyot",
            "Madaniyat",
            "Mehnatobod",
            "Mo'yinqum",
            "Xos",
            "Chanoq",
            "Yangi hayot",
            "Yangiqo'rg'on"
        ],
        "Bekabod shahri": [],
        "Bo'ka tumani": [
            "Bo'ka",
            "Iftixor",
            "Ko'korol",
            "Qoraqo'yli",
            "Qo'shtepa",
            "Namuna",
            "Rovot",
            "Turon",
            "Chig'atoy"
        ],
        "Bo'stonliq tumani": [
            "Azadbash",
            "Bog'iston",
            "Burchmullo",
            "Bo'stonliq",
            "G'azalkent",
            "G'azalkent",
            "Dumaloq",
            "Iskandar",
            "Qoramanas",
            "Qoronqul",
            "Qurbonov nomli",
            "Qo'shqo'rg'on",
            "Qo'shqo'rg'on",
            "Nanay",
            "Pargos",
            "Pargos",
            "Pskom",
            "Sari qanli",
            "Sijjak",
            "Sobir Raximov",
            "Soyliq",
            "Soyliq",
            "Talpin",
            "Tulabe",
            "Uenqulsoy",
            "Xondoyliq",
            "Xo'jakent",
            "Xo'jakent",
            "Xumsan",
            "Xumsan",
            "Ho'ja",
            "Chimboyliq",
            "Chimgan",
            "Chinor",
            "Chorvoq",
            "Yangi ovul"
        ],
        "Zangiota tumani": [
            "Axmad Yassaviy",
            "Boz-su",
            "Daliguzar",
            "Zangiota",
            "Zangiota",
            "Qatortol",
            "Quyoshli",
            "Nazarbek",
            "Nazarbek",
            "Pastdarxon",
            "Tarnov",
            "Turkiston",
            "O'zgarish",
            "Ulug'bek",
            "O'rtaovul",
            "Xonabod",
            "Honobod",
            "Chig'atoy-Oqtepa",
            "Erkin",
            "Erkin",
            "Eshonguzar"
        ],
        "Qibray tumani": [
            "Alisherobod",
            "Argin",
            "Baytqo'rg'on",
            "Geofizika",
            "Do'rmon",
            "Do'rmon",
            "Yon-ariq",
            "Yoshlik",
            "Zafarobod",
            "Ko'prik boshi",
            "Qibray",
            "Qipchoq",
            "Madaniyat",
            "Mustaqillik",
            "Nurafshon",
            "Oq-qovoq",
            "Salar",
            "TaraqQiyot",
            "Tuzel",
            "Uymaut",
            "Unqo'rg'on",
            "Unqo'rg'on-1",
            "O'tkir",
            "X.Amirov",
            "Chinobod",
            "Yangiobod"
        ],
        "Quyichirchiq tumani": [
            "Gul",
            "Do'stobod",
            "Ketmontepa",
            "Qo'rg'oncha",
            "Qo'rg'oncha",
            "Maydontol",
            "Ma?naviyat",
            "Ma?rifat",
            "Paxtazor",
            "Toshloq",
            "Toshovul",
            "O'zbekiston"
        ],
        "Oqqo'rg'on tumani": [
            "Achchi",
            "Do'stlik",
            "Zarbdor",
            "Zafar",
            "Oytamg'ali",
            "Oqqo'rg'on",
            "Oqqo'rg'on",
            "Olimkent",
            "Toshto'g'on",
            "Hamzaobod",
            "Shoxruxiya",
            "Eltamg'ali",
            "Erkinlik"
        ],
        "Olmaliq shahri": [],
        "Ohangaron tumani": [
            "Birlik",
            "Do'stlik",
            "Yon-ariq",
            "Qora xitoy",
            "Qora Xitoy",
            "Qurama",
            "Ozodlik",
            "Susam",
            "Telov",
            "Telov",
            "Uvaq",
            "Eyvalek"
        ],
        "Parkent tumani": [
            "Boshqizilsoy",
            "Bo'ston",
            "Zarkent",
            "Qoraqalpoq",
            "Quyosh",
            "Qo'rg'ontepa",
            "Nomdanak",
            "Parkent",
            "Parkent",
            "So'qoq",
            "Xisarak",
            "Changi",
            "Chinorli"
        ],
        "Piskent tumani": [
            "Dungqo'rg'on",
            "Kelovchi",
            "Koriz",
            "Muratali",
            "Murotali",
            "Oq tepa",
            "Pskent",
            "Said",
            "Said"
        ],
        "O'rtachirchiq tumani": [
            "Angor",
            "Istiqbol",
            "Yo'ng'ichqala",
            "Kuchluk",
            "Qorasuv",
            "Qorasuv",
            "Qumovul",
            "Navoiy nomli",
            "Oq ota",
            "Paxtakor",
            "Paxtaobod",
            "Tuyabo'g'iz",
            "Uyshun",
            "O'rtasaroy",
            "Haqiqat",
            "Sholikor",
            "Yangi turmush"
        ],
        "Chinoz tumani": [
            "A.Temur",
            "Birlik",
            "Gulzorobod",
            "Do'stlik",
            "Yollama",
            "Isloxat",
            "Kir",
            "Ko'tarma",
            "Olmazor",
            "Paxta",
            "Turkiston",
            "O'zbekiston",
            "Chinoz",
            "Chinoz",
            "Chorvador",
            "Eski Toshkent",
            "Eshonobod",
            "Yangi Chinoz"
        ],
        "Chirchiq shahri": [],
        "Yuqorichirchiq tumani": [
            "Arganchi",
            "Bordonko'l",
            "Jambul",
            "Istiqlol",
            "Mirobod",
            "Navro'z",
            "Oqovul",
            "Sakson ota",
            "Surnkent",
            "Tinchlik",
            "Xitoy Tepa",
            "Yangibozor"
        ],
        "Yangiyo'l tumani": [
            "Bozsu",
            "Gulbahor",
            "Yo'g'ontepa",
            "Kirsadoq",
            "Qovunchi",
            "Qo'sh yog'och",
            "Navbahor",
            "Niyozbosh",
            "Nov",
            "Xonqo'rg'on",
            "Halqobod",
            "Sho'ralisoy",
            "Eski Qovunchi"
        ],
        "Ohangaron shahri": [],
        "Yangiyo'l shahri": [],
        "Toshkent tumani": [
            "Guliston",
            "Z.Jalilov",
            "Keles",
            "Kensoy",
            "Ko'k saroy",
            "Ko'k Saroy",
            "Ko'k-terak",
            "Qashqarlik",
            "Qizg'aldoq",
            "M.Fozilov",
            "Masalboy",
            "Sabzavot",
            "Hasanboy",
            "Hasanboy",
            "Chig'atoy",
            "Choshtepa",
            "Chuvalachi",
            "Shamsiobod",
            "Yunusobod"
        ]
    },
    "Farg'ona viloyati": {
        "Beshariq tumani": [
            "Beshariq",
            "Nafosat",
            "Zarqaynar",
            "Kapayangi",
            "Qumqishloq",
            "Oqtovuq",
            "Rapqon",
            "Tovul",
            "Uzun",
            "Chimboy",
            "Manguobod",
            "Beshariq tumanining qishloq fuqarolar yig'inlari",
            "Andarxon",
            "Beshariq",
            "Vatan",
            "Qorajiyda",
            "Qashqar",
            "Beshsari",
            "Rapqon",
            "Tovul",
            "Yakkatut"
        ],
        "Bog'dod tumani": [
            "Bog'dod",
            "Amirobod",
            "Maylavoy",
            "Oltin vodiy",
            "Bog'ishamol",
            "Bordon",
            "Do'rmoncha",
            "Irgali",
            "Qaroqchitol",
            "Kaxat",
            "Qirqboldi",
            "Konizar",
            "Qo'shtegirmon",
            "Matqulobod",
            "Mirzaobod",
            "Samandarak",
            "Samarqand",
            "O'ltarma",
            "Xusnobod",
            "Chekmirzaobod",
            "Churindi"
        ],
        "Buvayda tumani": [
            "Ibrat",
            "Yuqori Bachqir",
            "Quyi Bachqir",
            "Chinobod",
            "Buvayda",
            "Zarbuloq",
            "Qum",
            "Yuqori Nayman",
            "Oqqo'rg'on",
            "Quyi Urganji"
        ],
        "Dang'ara tumani": [
            "Dang'ara",
            "Doimobod",
            "Katta Ganjiravon",
            "Katta Turk",
            "Qum Qiyali",
            "Toptiqsaroy",
            "Tumor",
            "Yuqori Urganji",
            "Yangi zamon"
        ],
        "Yozyovon tumani": [
            "Yozyovon",
            "Yozyovon chek",
            "Yo'ldoshobod",
            "Qorasoqol",
            "Qoratepa",
            "Kelajak",
            "Quyi Soybo'yi",
            "Toshxovuz",
            "Xonobod"
        ],
        "Quva tumani": [
            "Quva",
            "Sanoatchilar",
            "Guliston",
            "Damariq",
            "Jalayer",
            "Qayirma",
            "Qaqir",
            "Qandabuloq",
            "Qorashox",
            "Mustaqillik",
            "Oltinariq",
            "Pastki Xo'ja Xasan",
            "Tolmozor",
            "Turk",
            "O'zbek",
            "Yuziya"
        ],
        "Quvasoy shahri": [
            "Arsif",
            "Valik",
            "Qo'chqorchi",
            "Muyon",
            "Isfayramsoy",
            "So'fon"
        ],
        "Qo'qon shahri": [
            "Muqimiy"
        ],
        "Qo'shtepa tumani": [
            "Boltako'l",
            "Gishtmon",
            "Do'rmon",
            "Katta Beshkapa",
            "Qizil ariq",
            "Qorajiyda",
            "Qorakaltak",
            "Qumtepa",
            "Quyi Oqtepa",
            "Sarmozor",
            "Xotinariq",
            "Shahartepa",
            "Eshonguzar",
            "Yangiariq"
        ],
        "Marg'ilon shahri": [
            "Yangi Marg'ilon"
        ],
        "Oltiariq tumani": [
            "Oltiariq",
            "Chinor",
            "Azimobod",
            "Bo'rbaliq",
            "Djurek",
            "Zilxa",
            "Katput",
            "Oqbo'yra",
            "Povulg'on",
            "Poloson",
            "Chordara",
            "Eskiarab",
            "Yangiarab",
            "Yangiqo'rg'on",
            "Yangiyo'l tumanining qishloq fuqarolar yig'inlari",
            "Oqbo'yra",
            "Oltiariq",
            "Yangiarab",
            "Bo'rbaliq",
            "G'ayrat",
            "Djurek",
            "Qiziltepa",
            "Poloson",
            "Fayziobod",
            "Toshqo'rg'on",
            "Kapchugay",
            "Povulg'on",
            "Katput",
            "Zilxa",
            "Azimobod",
            "Tinchlik"
        ],
        "Rishton tumani": [
            "Rishton",
            "Avazboy",
            "Beshkapa",
            "Bujay",
            "Bo'ston",
            "Do'tir",
            "Saxovat",
            "Zoxidon",
            "Qayrag'och",
            "Oq-yer",
            "Pandigon",
            "To'da",
            "O'yrat",
            "Xurramobod"
        ],
        "So'x tumani": [
            "Ravon",
            "Qal'a",
            "Sarikanda",
            "So'x",
            "Tul",
            "Hushyor",
            "Tarovatli"
        ],
        "Toshloq tumani": [
            "Toshloq",
            "Arabmozor",
            "Axshak",
            "Varzak",
            "Zarkent",
            "Qumariq",
            "Quyi Nayman",
            "Sadda",
            "Turvat",
            "Yakkatut"
        ],
        "Uchko'prik tumani": [
            "Uchko'prik",
            "Begobod",
            "G'ijdan",
            "Katta Qashqar",
            "Qumariqobod",
            "Bog'ibo'ston",
            "Mirzaxo'ja",
            "Palaxon",
            "Sobirjon",
            "Turg'oq",
            "Yangiqishloq"
        ],
        "O'zbekiston tumani": [
            "Yaypan",
            "Sho'rsuv",
            "Avg'on",
            "Dahana Qaqir",
            "Islom",
            "Katta Tagob",
            "Qizil Qaqir",
            "Kichik Tagob",
            "Sardoba",
            "Kudash",
            "Kul elash",
            "Qulibek",
            "Qumbosti",
            "Qo'shqo'noq",
            "Qo'rg'oncha",
            "Nursux",
            "Ovchi",
            "Oyimcha Qaqir",
            "Oqmachit",
            "Oxta Tagob",
            "O'qchi Dasht",
            "O'qchi Rajabgardi",
            "Iftixor"
        ],
        "Farg'ona tumani": [
            "Chimyon ( mavjud)",
            "Avval",
            "Archa",
            "Vodil",
            "Yuqori Vodil",
            "Damko'l",
            "Yoshlarobod",
            "Qo'rg'ontepa",
            "Langar",
            "Log'on",
            "Mindon",
            "Novkent",
            "Yuqori Oqtepa",
            "Parvoz",
            "Yuqori Soybo'yi",
            "Bahor",
            "Xonqiz",
            "Xo'roba",
            "Neftchilar",
            "Shoximardonobod",
            "Yuqori Mindon"
        ],
        "Farg'ona shahri": [],
        "Furqat tumani": [
            "Navbahor",
            "Kaldo'shan",
            "Qo'qonboy",
            "Tomosha",
            "Chek chuvaldak",
            "Shoyinbek",
            "Eski",
            "Eshon"
        ]
    },
    "Xorazm viloyati": {
        "Bog'ot tumani": [
            "Bog'ot",
            "Nurafshon",
            "Oltinqum",
            "Uzumzor",
            "Yangiqadam"
        ],
        "Gurlan tumani": [
            "Gurlan",
            "Chakkalar",
            "Bo'zqal'a",
            "Nurzamin",
            "Nukus yop",
            "Markaziy Guliston",
            "Do'simbiy",
            "Taxtako'pir",
            "Yormish"
        ],
        "Qo'shko'pir tumani": [
            "Qo'shko'pir",
            "Qoromon",
            "O'rta qishloq",
            "Xonbod",
            "Shixmashhad",
            "Sherobod"
        ],
        "Urganch tumani": [
            "Cholish",
            "Oq oltin",
            "Chandir",
            "Ko'palik",
            "Gardonlar"
        ],
        "Urganch shahri": [],
        "Xiva tumani": [
            "Gullanbog'",
            "Parchanxos",
            "Iftixor",
            "Sho'r-Qal'a",
            "Yuqori qo'm",
            "Hamkor"
        ],
        "Xazarasp tumani": [
            "Xazorasp",
            "Oq yop",
            "Oyok ovvo",
            "Nurxayot"
        ],
        "Xonqa tumani": [
            "Xonqa",
            "Istiqlol",
            "Madaniy yer",
            "Birlashgan",
            "Yosh kuch"
        ],
        "Shavot tumani": [
            "Shovot",
            "Bo'yrochi",
            "Ipakchi",
            "Kangli",
            "Qat-qal'a",
            "Monoq",
            "Chig'atoy"
        ],
        "Yangiariq tumani": [
            "Yangiariq",
            "Gulbog'",
            "Soburzon",
            "Suvgan",
            "Tagan",
            "Qo'shloq"
        ],
        "Yangibozor tumani": [
            "Yangibozor",
            "Yangi yop",
            "Mangitlar"
        ],
        "Xiva shahri": [],
        "Do'stlik shahri": [],
        "Tuproqqala tumani": [
            "Pitnak"
        ]
    },
    "Toshkent shahri": {
        "Bektimer tumani": [],
        "Mirzo Ulug'bek tumani": [
            "Ulug'bek"
        ],
        "Mirobod tumani": [],
        "Olmazor tumani": [],
        "Sirg'ali tumani": [],
        "Uchtepa tumani": [],
        "Yashnobod tumani": [],
        "Chilonzor tumani": [],
        "Shayxontohur tumani": [],
        "Yunusobod tumani": [],
        "Yakkasaroy tumani": [],
        "Yangihayot tumani": []
    }
}


     // Modal
     let modal = document.getElementById("myModal");
     let closedBtn = document.getElementById("closed-btn");
     let rozilik = document.getElementById("rozilik");
     let btn = document.getElementById("myBtn");
     var span = document.getElementsByClassName("close")[0];
     window.onload = function() {
         modal.style.display = "block";
         closedBtn.disabled = true;
     }
     function myFunction() {
         closedBtn.disabled = false;
     }
     closedBtn.onclick = function() {
         modal.style.display = "none";
     }   
     


window.onload = function () {
    
    // FAKULTET
    const fakultetSelection = document.querySelector("#fakultet"),
    majorSelection = document.querySelector("#major");
    
    // todo: Disable all  Selection by setting disabled to false
    majorSelection.disabled = true;
    
    for (let fakultet in fakultetName) {
        fakultetSelection.options[fakultetSelection.options.length] = new Option(
            fakultet,
            fakultet
            );
        }
        // Region Changed
        fakultetSelection.onchange = (e) => {
            majorSelection.disabled = false;
            
            majorSelection.length = 1;
            
            // Load states by looping over fakultet
            for (let major of fakultetName[e.target.value]) {
                majorSelection.options[majorSelection.options.length] = new Option(
                    major,
                    major
                    );
                }
            };
            
            
            
    // REGION
    const regionSelection = document.querySelector("#region"),
    districtSelection = document.querySelector("#district");
    
    // todo: Disable all  Selection by setting disabled to false
    districtSelection.disabled = true;
    
    for (let region in regionStateInfo) {
        regionSelection.options[regionSelection.options.length] = new Option(
            region,
            region
            );
        }
        // Region Changed
        regionSelection.onchange = (e) => {
            districtSelection.disabled = false;
            
            districtSelection.length = 1;
            
            // Load states by looping over regionStateInfo
            for (let district in regionStateInfo[e.target.value]) {
                districtSelection.options[districtSelection.options.length] = new Option(
                    district,
                    district
                    );
                }
            };
                    
                    
                    
     //Uppercase
     const inputField = document.getElementById("seriya");    
     inputField.addEventListener("keyup", function(event) {
         event.preventDefault();
         inputField.value = inputField.value.toUpperCase();
         inputField.value.length = 2;
     });
};
                